AWSTemplateFormatVersion: '2010-09-09'
Description: Jenkins EC2 Setup on Amazon Linux 2023 (Ohio Region)
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: AWS::EC2::KeyPair::KeyName
Resources:
  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and Jenkins access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp: 0.0.0.0/0
  JenkinsInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-06d4b7182ac3480fa
      SecurityGroups:
      - Ref: JenkinsSecurityGroup
      KeyName:
        Ref: KeyName
      UserData:
        Fn::Base64: "#!/bin/bash\n\n# Update system packages\nsudo dnf update -y\n\
          \n# Install Java 11 (required for Jenkins)\nsudo dnf install java-17-amazon-corretto\
          \ -y\nsudo alternatives --config java\njava -version\n\n# Import Jenkins\
          \ repository and GPG key\nsudo curl --silent --location https://pkg.jenkins.io/redhat-stable/jenkins.repo\
          \ -o /etc/yum.repos.d/jenkins.repo\nsudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key\n\
          \n# Install Jenkins\nsudo dnf install jenkins -y\n\n# Enable and start Jenkins\
          \ service\nsudo systemctl enable jenkins\nsudo systemctl start jenkins\n\
          sudo systemctl restart jenkins\nsudo systemctl status jenkins\n\n# Optionally\
          \ install firewalld and open port 8080\nif ! command -v firewall-cmd &>\
          \ /dev/null\nthen\n    echo \"Installing firewalld...\"\n    sudo dnf install\
          \ firewalld -y\n    sudo systemctl enable firewalld\n    sudo systemctl\
          \ start firewalld\nfi\n\n# Open port 8080 for Jenkins\nsudo firewall-cmd\
          \ --permanent --zone=public --add-port=8080/tcp\nsudo firewall-cmd --reload\n\
          \necho \"Jenkins installation completed. Access it via http://<your-ec2-public-ip>:8080\"\
          \n"
Outputs:
  InstancePublicIP:
    Description: Public IP of the Jenkins EC2 instance
    Value:
      Fn::GetAtt:
      - JenkinsInstance
      - PublicIp
